name: Build Godot Game

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "scenes/**"
      - "scripts/**"
      - "sprites/**"
      - "Main.tscn"
      - "project.godot"
      #- "ans/answers.json"
      # Uncomment when we get to this stage.
  pull_request:
    branches: [ main ]
    paths:
      - "scenes/**"
      - "scripts/**"
      - "sprites/**"
      - "Main.tscn"
      - "project.godot"
      #- "ans/answers.json"
      # Uncomment when we get to this stage.
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Export Godot project
      uses: mirror12k/godot-export-build@v1
      with:
        godot-version: '4.2.1'
        project-path: '.'

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: builds
        path: build/*
