name: Build & release Godot Game

on:
  push:
    tags:
        - "v*"
  
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Wine for Windows EXE logo
      id: wine_install
      run: |
        sudo apt install wine64
        echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

    - name: Export Godot project
      id: export
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
        relative_project_path: '.'
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
    
    - name: Upload production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: StarJump builds
        path: ${{ steps.export.outputs.build_directory }}/*

    - name: Create release
      uses: ncipollo/release-action@v1.14.0
      with:
        name: "StarJump ${{ github.ref_name }}"
        body: "Supports Windows only. Linux & MacOS support *may* come at a later date."
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.build_directory }}/*
        draft: true